#!/usr/bin/env bash

export SCRIPTPATH="$(
    cd "$(dirname "$0")"
    pwd -P
)"

POLYBAR_LAUNCHER="$HOME/.config/polybar/launch.sh"
WALLPAPER_SETTER="$HOME/.config/leftwm/scripts/set-wallpaper"
SCREENLAYOUT_SETTER="$HOME/.config/screenlayout/default.sh"

# down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
    picom --daemon &>/dev/null &
elif [ -x "$(command -v compton)" ]; then
    compton &>/dev/null &
fi

clipcatd

# set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

$SCREENLAYOUT_SETTER

# set background
$WALLPAPER_SETTER &

# launch polybar
$POLYBAR_LAUNCHER
