require("nvim-treesitter.configs").setup({
    ensure_installed = {
        "bash",
        "c",
        "cmake",
        "cpp",
        "dockerfile",
        "git_rebase",
        "gitignore",
        "go",
        "hcl",
        "html",
        "http",
        "javascript",
        "json",
        "lua",
        "make",
        "markdown",
        "nix",
        "proto",
        "python",
        "query",
        "rust",
        "sql",
        "toml",
        "typescript",
        "yaml",
    },
    auto_install = true,
    autotag = {
        enable = true,
    },
    highlight = {
        enable = true,
        disable = { "html" },
        additional_vim_regex_highlighting = false,
    },
    ident = { enable = true },
    rainbow = { enable = true, extended_mode = true, max_file_lines = nil },
})
